##NUMPY

numpy aims to provide  an array  object that is upto 50 x faster than traditional lists.
Numpy arrays are stored at one continous place in memory unlike lists so processes can access and manipulate them very efficiently.

In [1]:
import numpy as np;
a = np.array([1,2,22,3])

In [2]:
for i in range (len(a)):
    print(i*7)

0
7
14
21


In [3]:
import numpy as np;
# Create a 2D array
matrix = np.array([[1, 2], [3, 4]])
print("2D Array:\n", matrix)

# Accessing elements
print("Element at row 0, column 1:", matrix[0, 1])  # Output: 2
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)        # [11 22 33]
print("Multiplication:", a * b)  # [10 40 90]
print("Mean of a:", np.mean(a))  # 20.0



2D Array:
 [[1 2]
 [3 4]]
Element at row 0, column 1: 2
Addition: [11 22 33]
Multiplication: [10 40 90]
Mean of a: 20.0


In [4]:
import numpy as np;
# Create a 3x3 matrix with random values
rand_matrix = np.random.rand(3, 3)
print("Random Matrix:\n", rand_matrix)

# Reshape a flat array to 2D
flat = np.arange(9)
reshaped = flat.reshape(3, 3)
print("Reshaped Array:\n", reshaped)


Random Matrix:
 [[0.48194432 0.28769071 0.51659156]
 [0.19471156 0.37474759 0.33213113]
 [0.27002499 0.29515092 0.88684183]]
Reshaped Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
import numpy as np;
arr = np.array([5, 10, 15, 20, 25])
filtered = arr[arr > 15]
print("Filtered (greater than 15):", filtered)  # [20 25]


Filtered (greater than 15): [20 25]


In [6]:
import numpy as ss;
arr1 = ss.array([2,3,4,5,5]);
for i in range (len(arr1)):
    if i==1 :
        print(arr1[i])


3


In [1]:
import numpy as np

# Step 1: Define two arrays
array1 = [1, 3, 5, 7, 9]
array2 = [2, 3, 5, 8, 10]

# Step 2: Get the union (remove duplicates)
union_array = list(set(array1 + array2))
union_array.sort()

# Step 3: Calculate mean and median
mean_val = np.mean(union_array)
median_val = np.median(union_array)

# Step 4: Print results
print("Array 1:", array1)
print("Array 2:", array2)
print("Union:", union_array)
print("Mean:", mean_val)
print("Median:", median_val)


Array 1: [1, 3, 5, 7, 9]
Array 2: [2, 3, 5, 8, 10]
Union: [1, 2, 3, 5, 7, 8, 9, 10]
Mean: 5.625
Median: 6.0
